# Generated by Django 4.2.2 on 2023-06-14 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songreviewcomment',
            old_name='song_review',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='songreviewlike',
            old_name='song_review',
            new_name='review',
        ),
    ]
